export enum Permission {
    MANAGE_CUSTOMERS = 'MANAGE_CUSTOMERS',
    MANAGE_CONTACT_MESSAGES = 'MANAGE_CONTACT_MESSAGES',
    MANAGE_SERVICE = 'MANAGE_SERVICE',
    MANAGE_UPLOAD = 'MANAGE_UPLOAD',
    MANAGE_BLOG = 'MANAGE_BLOG',
    MANAGE_PAYMENTS = 'MANAGE_PAYMENTS',
    MANAGE_EMAIL_SUBSCRIPTIONS = 'MANAGE_EMAIL_SUBSCRIPTIONS',
}